server:
  port: 10010
  servlet:
    #配置session过期时间
    session:
      timeout: 30m
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 8.140.250.3
    port: 6124
    password: qwerty123456
  session:
    store-type: redis